### ISSUE TITLE
Can't find settings.py file

### ISSUE THREAD

**Issue by kutibotond** [aru-py/philips-hue-midi#1]
Hello, I'd really like to get this working.

I followed the instructions from the read me but I can't find where I should replace the placeholders, there's no settings.py that I can see.

**Comment by aru-py** [comment]
@kutibotond Hey there! I'll add some more documentation on how to use the program this week.

In the meantime, you need to create a config.example.toml that looks like:

```
bridge_ip = '192.168.1.14'
palette = ["2C3D21B", "1212168E", "21D87B8", "91AFD7", "21217AA1"]

[channels.default]
lights = []
brightness = { off_min = 0, on_min = 10, entropy = 20, sensitivity = 12 }
transition = { min = 21 }
colors = [[0.5881, 0.386], [0.5246, 0.4135]]

# color and bulb 1
[channels.0]
lights = [1, 2, 3, 4, 6, 8]

[channels.1]
lights = [1, 8]
```

Let me know what issues you're running into.

**Comment by aru-py** [comment]
@kutibotond Hey, sorry for the delay! I updated the README.md with clearer instructions. Let me know if you are able to get it working and if anything can be improved. Thanks!
